export const PERMISSIONS = {
  ORG_READ: "ORG_READ",
  ORG_UPDATE: "ORG_UPDATE",
  ORG_DELETE: "ORG_DELETE",
  ORG_MEMBER_READ: "ORG_MEMBER_READ",
  ORG_MEMBER_INVITE: "ORG_MEMBER_INVITE",
  ORG_MEMBER_UPDATE: "ORG_MEMBER_UPDATE",
  ORG_MEMBER_REMOVE: "ORG_MEMBER_REMOVE",
  ORG_ROLE_READ: "ORG_ROLE_READ",
  ORG_ROLE_MANAGE: "ORG_ROLE_MANAGE",
  ORG_TEAM_READ: "ORG_TEAM_READ",
  ORG_TEAM_MANAGE: "ORG_TEAM_MANAGE",
  ORG_API_KEY_MANAGE: "ORG_API_KEY_MANAGE",
  BILLING_READ: "BILLING_READ",
  BILLING_MANAGE: "BILLING_MANAGE",
  BILLING_INVOICE_DOWNLOAD: "BILLING_INVOICE_DOWNLOAD",
  AUDIT_READ: "AUDIT_READ",
  FILE_READ: "FILE_READ",
  FILE_UPLOAD: "FILE_UPLOAD",
  FILE_DELETE: "FILE_DELETE",
  CHAT_READ: "CHAT_READ",
  CHAT_READ_ALL: "CHAT_READ_ALL",
  CHAT_REPLY: "CHAT_REPLY",
  CHAT_ASSIGN: "CHAT_ASSIGN",
  CHAT_MANAGE: "CHAT_MANAGE",
  VISITOR_READ: "VISITOR_READ",
  VISITOR_ANALYTICS: "VISITOR_ANALYTICS",
  VISITOR_MANAGE: "VISITOR_MANAGE",
  LOG_READ: "LOG_READ",
  LOG_EXPORT: "LOG_EXPORT",
  COMMERCE_CATALOG_READ: "COMMERCE_CATALOG_READ",
  COMMERCE_CATALOG_MANAGE: "COMMERCE_CATALOG_MANAGE",
  COMMERCE_ORDER_READ: "COMMERCE_ORDER_READ",
  COMMERCE_ORDER_MANAGE: "COMMERCE_ORDER_MANAGE",
  COMMERCE_ORDER_REFUND: "COMMERCE_ORDER_REFUND",
  COMMERCE_CUSTOMER_READ: "COMMERCE_CUSTOMER_READ",
  COMMERCE_DISCOUNT_MANAGE: "COMMERCE_DISCOUNT_MANAGE",
  COMMERCE_SETTINGS_MANAGE: "COMMERCE_SETTINGS_MANAGE",
  AI_USE: "AI_USE",
  AI_CONFIGURE: "AI_CONFIGURE",
  AI_USAGE_READ: "AI_USAGE_READ",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export function hasPermission(
  permissions: string[],
  required: Permission | Permission[],
): boolean {
  const requiredList = Array.isArray(required) ? required : [required];
  return requiredList.every((p) => permissions.includes(p));
}

export function hasAnyPermission(
  permissions: string[],
  required: Permission[],
): boolean {
  return required.some((p) => permissions.includes(p));
}
